# Install Apache or Httpd based on OS
- name: Install "{{ web_package }}"
  ansible.builtin.package:
    update_cache: yes
    name: "{{ web_package }}"
    state: present

# Start and enable web service
- name: Start "{{ web_service }}"
  ansible.builtin.service:
    name: "{{ web_service }}"
    state: started
    enabled: yes

# Deploy homepage template
- name: Deploy index file
  ansible.builtin.template:
    src: "{{ web_index_template }}"
    dest: "{{ web_root }}/index.html"